var1 = [1, 2, 3, 4]

1. Print tipe dari var1

2. Print panjang dari var1

In [63]:
var1 = [1,2,3,4]
print("tipe dari list var1 adalah ",type(var1))

print("elemen-elemen asli var1 : ",var1)

tipe dari list var1 adalah  <class 'list'>
elemen-elemen asli var1 :  [1, 2, 3, 4]


In [7]:
print("banyaknya elemen adalah ",len (var1))

banyaknya elemen adalah  4


first = [11.25, 18.0, 20.0] 

second = [10.75, 9.50]

3. Gabungkan list first dengan second simpan dengan nama variabel full, print vraiabel full

4. Urutkan full dengan descending order simpan pada variabel full_sorted, print full_sorted

In [64]:
first=[11.25,18.0,20.0]
second=[10.75,9.50]
variabel_full=first+second
print("gabungan list first dan second adalah ",variabel_full)

gabungan list first dan second adalah  [11.25, 18.0, 20.0, 10.75, 9.5]


In [66]:
full_sorted=sorted(variabel_full, reverse=True)
print("urutan descending order yaitu ",full_sorted)

urutan descending order yaitu  [20.0, 18.0, 11.25, 10.75, 9.5]


area = [11.25, 18.0, 20.0, 10.75, 9.50]

5. Print hasilnya dengan menggunakan index() untuk mencari index dari 20.0 

6. Print  hasilnya dengan menggunakan count() berapa sering 14.5 muncul di area

7. Gunakan append dua kali untuk menambahkan 24.5 dan 15.45, print area

8. Balik urutan area dengan reverse(), print area


In [67]:
area=[11.25, 18.0, 20.0, 10.75, 9.5]

print(area[2])

20.0


In [68]:
print("14.5 muncul sebanyak ",area.count(14.5))

14.5 muncul sebanyak  0


In [72]:
area.append(24.5)
area.append(15.45)
print("Berikut update list area ",area)
del area[-2]
print("Berikut update list area ",area)

Berikut update list area  [11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 24.5, 15.45, 24.5, 15.45]
Berikut update list area  [11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 24.5, 15.45, 15.45]


In [74]:
del area[-3]
del area[-1]
print("Berikut update list area ",area)

Berikut update list area  [11.25, 18.0, 20.0, 10.75, 9.5, 24.5, 15.45]


In [80]:
print("Berikut urutan list area ",sorted(area, reverse=True))

Berikut urutan list area  [24.5, 20.0, 18.0, 15.45, 11.25, 10.75, 9.5]


Masih ingat tentang lingkaran?
$$ Keliling = 2\pi r $$
$$ Luas = \pi r^2 $$

- Kamu bisa mendapatkan pi dengan cara import math kemudian panggil dengan math.pi


r = 0.43

9. Hitung keliling simpan dalam variabel keliling

10. Hitung luas simpan dalam variabel luas

11. Selesaikan Print ini : print("Keliling: " + ) dan print("Luas: " + )

In [83]:
import math
print ("Nilai pi : ",math.pi)
r=0.43

Keliling=2*math.pi*r
print("Jadi keliling dari lingkaran tersebut adalah", Keliling)

Nilai pi :  3.141592653589793
Jadi keliling dari lingkaran tersebut adalah 2.701769682087222


In [84]:
Luas=math.pi*r*r
print("Jadi Luas dari lingkaran tersebut adalah", Luas)

Jadi Luas dari lingkaran tersebut adalah 0.5808804816487527


In [88]:
print("Keliling  : ",Keliling)
print("Luas      : ",Luas)

Keliling  :  2.701769682087222
Luas      :  0.5808804816487527


area_3 = ["hallway", 11.25, "kitchen", 18.0,
        "chill zone", 20.0, "bedroom", 10.75,
         "bathroom", 10.50, "poolhouse", 24.5,
         "garage", 15.45]

12. Silahkan hapus 4 elemen terakhir, print area_3

In [104]:
area_3 = ["hallway", 11.25, "kitchen", 18.0, "chill zone", 20.0, "bedroom", 10.75, "bathroom", 10.50, "poolhouse", 24.5, "garage", 15.45]
del area_3 [10:14]
print("Berikut update list area_3 :", area_3,"dengan banyak elemen", len(area_3))

Berikut update list area_3 : ['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5] dengan banyak elemen 10


area_4 = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

13. Ganti nilai dari "bathroom" menjadi 10.8, print area_4

14. Ganti "living room" menjadi "ruang tamu", print area_4

In [106]:
area_4 = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]

area_4[-1]=10.8

print("Berikut update data list area_4 ",area_4)

Berikut update data list area_4  ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0, 'bedroom', 10.75, 'bathroom', 10.8]


In [109]:
area_4[4]="ruang tamu"
    
print("Berikut update data list area_4 ",area_4)

Berikut update data list area_4  ['hallway', 11.25, 'kitchen', 18.0, 'ruang tamu', 20.0, 'bedroom', 10.75, 'bathroom', 10.8]


2024090001_Moch_Amin_Irwanto